export const FETCH_BOOKING_TYPES_FROM_SERVER = 'FETCH_BOOKING_TYPES_FROM_SERVER';

export const LOGIN = 'LOGIN';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const UPDATE_LOGIN_FIELDS = 'UPDATE_LOGIN_FIELDS';

export const LOAD_COMPANIES_FROM_SERVER = 'LOAD_COMPANIES_FROM_SERVER';

export const SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY';
export const UPDATE_CURRENT_COMPANY_FIELDS = 'UPDATE_CURRENT_COMPANY_FIELDS';
export const SAVE_CURRENT_COMPANY = 'SAVE_CURRENT_COMPANY';

export const SET_CURRENT_CLINIC = 'SET_CURRENT_CLINIC';
export const UPDATE_CURRENT_CLINIC_FIELDS = 'UPDATE_CURRENT_CLINIC_FIELDS';
export const SAVE_CURRENT_CLINIC = 'SAVE_CURRENT_CLINIC';

export const SET_CURRENT_DOCTOR = 'SET_CURRENT_DOCTOR';
export const UPDATE_CURRENT_DOCTOR_FIELDS = 'UPDATE_CURRENT_DOCTOR_FIELDS';
export const SAVE_CURRENT_DOCTOR = 'SAVE_CURRENT_DOCTOR';
export const UPLOAD_PHOTO_DOCTOR = 'UPLOAD_PHOTO_DOCTOR';
export const FETCH_ROSTER_OF_DOCTOR = 'FETCH_ROSTER_OF_DOCTOR';
export const REMOVE_BOOKING_TYPE_OF_DOCTOR = 'REMOVE_BOOKING_TYPE_OF_DOCTOR';
export const ADD_BOOKING_TYPE_OF_DOCTOR = 'ADD_BOOKING_TYPE_OF_DOCTOR';
export const REMOVE_CLINIC_OF_DOCTOR = 'REMOVE_CLINIC_OF_DOCTOR';
export const ADD_CLINIC_OF_DOCTOR = 'ADD_CLINIC_OF_DOCTOR';

export const ROSTER_OPEN_CLICK_DAY_MODAL = 'ROSTER_OPEN_CLICK_DAY_MODAL';
export const ROSTER_CLOSE_CLICK_DAY_MODAL = 'ROSTER_CLOSE_CLICK_DAY_MODAL';
export const ROSTER_OPEN_EVENT_DAY_MODAL = 'ROSTER_OPEN_EVENT_DAY_MODAL';
export const ROSTER_CLOSE_EVENT_DAY_MODAL = 'ROSTER_CLOSE_EVENT_DAY_MODAL';
export const ROSTER_UPDATE_MODAL_FIELD = 'ROSTER_UPDATE_MODAL_FIELD';
export const ROSTER_GENERATION = 'ROSTER_GENERATION';

export const FETCH_BOOKINGS_FOR_BOOKING = 'FETCH_BOOKINGS_FOR_BOOKING';
export const FETCH_DOCTORS_FOR_BOOKING = 'FETCH_DOCTORS_FOR_BOOKING';
export const UPDATE_FIELDS_FOR_CURRENT_BOOKING = 'UPDATE_FIELDS_FOR_CURRENT_BOOKING';

export const UPDATE_FIELDS_FOR_PATIENT_SEARCH = 'UPDATE_FIELDS_FOR_PATIENT_SEARCH';
export const FETCH_PATIENTS_FOR_PATIENT_SEARCH = 'FETCH_PATIENTS_FOR_PATIENT_SEARCH';
export const SET_PATIENT_FOR_PATIENT_SEARCH = 'SET_PATIENT_FOR_PATIENT_SEARCH';

export const UPDATE_FIELDS_FOR_PATIENT_DETAIL = 'UPDATE_FIELDS_FOR_PATIENT_DETAIL';
export const CREATE_PATIENT_FOR_PATIENT_DETAIL = 'CREATE_PATIENT_FOR_PATIENT_DETAIL';
export const SAVE_FOR_PATIENT_DETAIL = 'SAVE_FOR_PATIENT_DETAIL';
