export const FETCH_BOOKING_TYPES_FROM_SERVER = 'FETCH_BOOKING_TYPES_FROM_SERVER';
export const SET_CLICKED_BOOKING_TYPE = 'SET_CLICKED_BOOKING_TYPE';

export const LOGIN = 'LOGIN';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const UPDATE_LOGIN_FIELDS = 'UPDATE_LOGIN_FIELDS';
